### ISSUE TITLE
Application repeated crashes 

### ISSUE THREAD

**Issue by PaulRead** [IBM-Bluemix/sphero-bluemix-remotecontrol#3]
I think that I have followed the instructions as per the readme.md however when I run cf push I get a series of errors in the logs and it finally fails with code 8 app crashed. 
I may be missing something very simple here according to the logs the first message I get is createClient is deprecated. I also noticed in the credentials pic the org (irnwk2) is part of the apiKey but my apiKey does not!

**Comment by jthomas** [comment]
Can you paste the logs in here?

**Comment by PaulRead** [comment]
James,
      When I revisited my app I noticed that I was using eu-gb and not ng I suspect that this may be my problem.  I will close this issue and restart my app development on ng.
